library("pROC")

# read in the data generated by the jupiter notebooks
data_biggest_2_6 <- read.csv("../Output/AUC_curve_averages_biggest.csv", header = TRUE, stringsAsFactors = FALSE)
data_biggest_0_3 <- read.csv("../Output/AUC_curve_averages_biggest_cut_03.csv", header = TRUE, stringsAsFactors = FALSE)

data_random_2_6 <- read.csv("../Output/AUC_curve_averages_random10.csv", header = TRUE, stringsAsFactors = FALSE)
data_random_0_3 <- read.csv("../Output/AUC_curve_averages_random10_cut_03.csv", header = TRUE, stringsAsFactors = FALSE)

data_best_2_6 <- read.csv("../Output/AUC_curve_averages_best.csv", header = TRUE, stringsAsFactors = FALSE)
data_best_0_3 <- read.csv("../Output/AUC_curve_averages_best_cut_03.csv", header = TRUE, stringsAsFactors = FALSE)


# perform the ROC analysis
roc_medians_biggest_2_6 <- roc(as.formula("truth ~ prediction"), data_biggest_2_6, direction = ">")
roc_medians_biggest_0_3 <- roc(as.formula("truth ~ prediction"), data_biggest_0_3, direction = ">")

roc_medians_random_2_6 <- roc(as.formula("truth ~ prediction"), data_random_2_6, direction = ">")
roc_medians_random_0_3 <- roc(as.formula("truth ~ prediction"), data_random_0_3, direction = ">")

roc_medians_best_2_6 <- roc(as.formula("truth ~ prediction"), data_best_2_6, direction = ">")
roc_medians_best_0_3 <- roc(as.formula("truth ~ prediction"), data_best_0_3, direction = ">")


# plot the ROC curves for the different cutoffs and PDB selections
pdf("./Plots/ROC_biggest_new.pdf",  width = 7, height = 7)
plot(roc_medians_biggest_2_6, auc.polygone = TRUE, cex.axis = 1.5, cex.lab = 1.5, col="#b0c7e0", lwd = 4, 
     main = paste("AUC 2.6: ", round(roc_medians_biggest_2_6$auc,2), " - AUC 0.3: ", round(roc_medians_biggest_0_3$auc, 2), sep = ''))
plot(roc_medians_biggest_0_3, auc.polygone = TRUE, cex.axis = 1.5, cex.lab = 1.5, col="#0057b7", lwd = 4, add = TRUE)
dev.off()


pdf("./Plots/ROC_random_new.pdf",  width = 7, height = 7)
plot(roc_medians_random_2_6, auc.polygone = TRUE, cex.axis = 1.5, cex.lab = 1.5, col="#b0c7e0", lwd = 4, 
     main = paste("AUC 2.6: ", round(roc_medians_random_2_6$auc,2), " - AUC 0.3: ", round(roc_medians_random_0_3$auc, 2), sep = ''))
plot(roc_medians_random_0_3, auc.polygone = TRUE, cex.axis = 1.5, cex.lab = 1.5, col="#0057b7", lwd = 4, add = TRUE)
dev.off()


pdf("./Plots/ROC_best_new.pdf",  width = 7, height = 7)
plot(roc_medians_best_2_6, auc.polygone = TRUE, cex.axis = 1.5, cex.lab = 1.5, col="#b0c7e0", lwd = 4, 
     main = paste("AUC 2.6: ", round(roc_medians_best_2_6$auc,2), " - AUC 0.3: ", round(roc_medians_best_0_3$auc, 2), sep = ''))
plot(roc_medians_best_0_3, auc.polygone = TRUE, cex.axis = 1.5, cex.lab = 1.5, col="#0057b7", lwd = 4, add = TRUE)
dev.off()


# summarize the number of peptides, peptides at interface, TPs and FPs in the respecitve datasets
get_numbers <- function(data){
  
  peptides <- nrow(data)
  peptides_interface <- length(which(data$truth ==1))
  TPs <- length(which(data$truth == 1  & data$prediction <= 0.05))
  FPs<- length(which(data$truth == -1  & data$prediction <= 0.05))

  return(c(peptides, peptides_interface, TPs, FPs))
}

nbs_random_2_6 <- get_numbers(data_random_2_6)
nbs_random_0_3 <- get_numbers(data_random_0_3)

nb_biggest_2_6 <- get_numbers(data_biggest_2_6)
nb_biggest_0_3 <- get_numbers(data_biggest_0_3)

nb_best_2_6 <- get_numbers(data_best_2_6)
nb_best_0_3 <- get_numbers(data_best_0_3)
